FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_ATTACHMENTS_BUCKET=attachments
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION=false
ARG VITE_GOOGLE_WORKPLACE_DOMAIN
ARG VITE_INBOUND_EMAIL
ARG VITE_IS_DEMO=false
ARG VITE_PRYMEIRA_ACCOUNT_API_URL
ARG VITE_PRYMEIRA_HUB_URL
ARG VITE_PRYMEIRA_PRODUCT_KEY=operis
ARG VITE_SB_PUBLISHABLE_KEY
ARG VITE_SUPABASE_URL

ENV VITE_ATTACHMENTS_BUCKET=$VITE_ATTACHMENTS_BUCKET
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION=$VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION
ENV VITE_GOOGLE_WORKPLACE_DOMAIN=$VITE_GOOGLE_WORKPLACE_DOMAIN
ENV VITE_INBOUND_EMAIL=$VITE_INBOUND_EMAIL
ENV VITE_IS_DEMO=$VITE_IS_DEMO
ENV VITE_PRYMEIRA_ACCOUNT_API_URL=$VITE_PRYMEIRA_ACCOUNT_API_URL
ENV VITE_PRYMEIRA_HUB_URL=$VITE_PRYMEIRA_HUB_URL
ENV VITE_PRYMEIRA_PRODUCT_KEY=$VITE_PRYMEIRA_PRODUCT_KEY
ENV VITE_SB_PUBLISHABLE_KEY=$VITE_SB_PUBLISHABLE_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/health || exit 1
