import type { AutomationRule } from "../../../types";

const now = "2026-05-20T00:00:00.000Z";

export const generateAutomationRules = (): AutomationRule[] => [
  {
    id: 1,
    rule_key: "lead.first-contact",
    name: "Lead sem próxima ação",
    description:
      "Cria tarefa de primeiro contato quando um lead nasce sem próxima ação.",
    enabled: true,
    trigger_resource: "leads",
    trigger_event: "created",
    condition_key: "missing_next_action",
    action_key: "create_task",
    params: {
      dueInDays: 0,
      taskType: "call",
      taskText: "Primeiro contato com {{lead.name}}",
      assignee: "record_owner",
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    rule_key: "deal.follow-up-required",
    name: "Negócio sem próxima ação",
    description: "Cria follow-up quando um negócio nasce sem próxima ação.",
    enabled: true,
    trigger_resource: "deals",
    trigger_event: "created",
    condition_key: "missing_next_action",
    action_key: "create_task",
    params: {
      dueInDays: 1,
      taskType: "follow-up",
      taskText: "Definir próximo passo: {{deal.name}}",
      assignee: "record_owner",
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    rule_key: "deal.proposal-follow-up",
    name: "Negócio em proposta enviada",
    description:
      "Cria follow-up quando o negócio entra na etapa Proposta enviada.",
    enabled: true,
    trigger_resource: "deals",
    trigger_event: "updated",
    condition_key: "stage_is_proposal_sent",
    action_key: "create_task",
    params: {
      dueInDays: 2,
      taskType: "follow-up",
      taskText: "Retomar proposta enviada: {{deal.name}}",
      assignee: "record_owner",
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    rule_key: "proposal.sent-follow-up",
    name: "Proposta enviada",
    description:
      "Cria follow-up depois que uma proposta é marcada como enviada.",
    enabled: true,
    trigger_resource: "proposals",
    trigger_event: "updated",
    condition_key: "status_is_sent",
    action_key: "create_task",
    params: {
      dueInDays: 2,
      taskType: "follow-up",
      taskText: "Acompanhar proposta: {{proposal.title}}",
      assignee: "record_owner",
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    rule_key: "proposal.accepted-action",
    name: "Proposta aceita",
    description: "Executa a ação configurada quando uma proposta é aceita.",
    enabled: true,
    trigger_resource: "proposals",
    trigger_event: "updated",
    condition_key: "status_is_accepted",
    action_key: "proposal_accepted_action",
    params: {
      acceptedAction: "move_deal_won",
      taskType: "follow-up",
      taskText: "Concluir fechamento da proposta: {{proposal.title}}",
      assignee: "record_owner",
    },
    created_at: now,
    updated_at: now,
  },
];
