import type { Company, RAFile } from "../../../types";
import type { Db } from "./types";

type CompanySeed = Omit<Required<Company>, "nb_contacts" | "nb_deals">;

const logo = (id: number, title: string) =>
  ({
    title,
    src: `https://marmelab.com/react-admin-crm/logos/${id}.png`,
  }) as RAFile;

const companies: CompanySeed[] = [
  {
    id: 0,
    name: "Grupo Aurora",
    logo: logo(0, "Grupo Aurora"),
    sector: "consumer-staples",
    size: 500,
    linkedin_url: "https://www.linkedin.com/company/grupo-aurora",
    website: "https://grupoaurora.com.br",
    phone_number: "+55 11 4002-1100",
    address: "Av. Brigadeiro Faria Lima, 1485",
    zipcode: "01452-002",
    city: "São Paulo",
    state_abbr: "SP",
    sales_id: 0,
    created_at: "2025-08-14T12:00:00.000Z",
    description:
      "Holding de varejo alimentar em expansão, com operação em múltiplas praças e time comercial descentralizado.",
    revenue: "R$ 180M",
    tax_identifier: "12.345.678/0001-90",
    country: "Brasil",
    context_links: ["https://grupoaurora.com.br/relatorio-anual"],
  },
  {
    id: 1,
    name: "Rede Vitta",
    logo: logo(1, "Rede Vitta"),
    sector: "health-care",
    size: 250,
    linkedin_url: "https://www.linkedin.com/company/rede-vitta",
    website: "https://redevitta.com.br",
    phone_number: "+55 31 3003-2200",
    address: "Rua dos Aimorés, 981",
    zipcode: "30140-071",
    city: "Belo Horizonte",
    state_abbr: "MG",
    sales_id: 1,
    created_at: "2025-09-03T12:00:00.000Z",
    description:
      "Rede de clínicas populares buscando padronizar atendimento, CRM e acompanhamento de pacientes corporativos.",
    revenue: "R$ 72M",
    tax_identifier: "23.456.789/0001-01",
    country: "Brasil",
    context_links: ["https://redevitta.com.br/empresas"],
  },
  {
    id: 2,
    name: "Lumen Energia",
    logo: logo(2, "Lumen Energia"),
    sector: "energy",
    size: 250,
    linkedin_url: "https://www.linkedin.com/company/lumen-energia",
    website: "https://lumenenergia.com.br",
    phone_number: "+55 41 3320-8844",
    address: "Av. Sete de Setembro, 2451",
    zipcode: "80230-010",
    city: "Curitiba",
    state_abbr: "PR",
    sales_id: 2,
    created_at: "2025-10-11T12:00:00.000Z",
    description:
      "Integrador de energia solar com funil consultivo longo e grande volume de propostas técnicas.",
    revenue: "R$ 96M",
    tax_identifier: "34.567.890/0001-12",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 3,
    name: "Atlas Contabilidade",
    logo: logo(3, "Atlas Contabilidade"),
    sector: "financials",
    size: 50,
    linkedin_url: "https://www.linkedin.com/company/atlas-contabilidade",
    website: "https://atlascontabil.com.br",
    phone_number: "+55 21 3555-0199",
    address: "Rua México, 31",
    zipcode: "20031-144",
    city: "Rio de Janeiro",
    state_abbr: "RJ",
    sales_id: 0,
    created_at: "2025-11-06T12:00:00.000Z",
    description:
      "Escritório contábil premium procurando organizar relacionamento com clientes recorrentes e parceiros.",
    revenue: "R$ 18M",
    tax_identifier: "45.678.901/0001-23",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 4,
    name: "NorteLog",
    logo: logo(4, "NorteLog"),
    sector: "industrials",
    size: 250,
    linkedin_url: "https://www.linkedin.com/company/nortelog",
    website: "https://nortelog.com.br",
    phone_number: "+55 92 3133-7070",
    address: "Av. Torquato Tapajós, 5555",
    zipcode: "69041-025",
    city: "Manaus",
    state_abbr: "AM",
    sales_id: 3,
    created_at: "2025-11-21T12:00:00.000Z",
    description:
      "Operador logístico regional com oportunidades em expansão, contratos anuais e múltiplos decisores por filial.",
    revenue: "R$ 124M",
    tax_identifier: "56.789.012/0001-34",
    country: "Brasil",
    context_links: ["https://nortelog.com.br/cases"],
  },
  {
    id: 5,
    name: "Estúdio Maralto",
    logo: logo(5, "Estúdio Maralto"),
    sector: "communication-services",
    size: 10,
    linkedin_url: "https://www.linkedin.com/company/estudio-maralto",
    website: "https://maralto.studio",
    phone_number: "+55 48 3207-4400",
    address: "Rua Bocaiúva, 2125",
    zipcode: "88015-530",
    city: "Florianópolis",
    state_abbr: "SC",
    sales_id: 4,
    created_at: "2025-12-02T12:00:00.000Z",
    description:
      "Estúdio de branding e conteúdo com alto volume de projetos e demanda por CRM simples para follow-up.",
    revenue: "R$ 4M",
    tax_identifier: "67.890.123/0001-45",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 6,
    name: "Flor de Sal Alimentos",
    logo: logo(6, "Flor de Sal Alimentos"),
    sector: "consumer-staples",
    size: 50,
    linkedin_url: "https://www.linkedin.com/company/flor-de-sal-alimentos",
    website: "https://flordesal.com.br",
    phone_number: "+55 85 3089-9090",
    address: "Av. Santos Dumont, 2828",
    zipcode: "60150-161",
    city: "Fortaleza",
    state_abbr: "CE",
    sales_id: 1,
    created_at: "2026-01-08T12:00:00.000Z",
    description:
      "Marca regional de alimentos naturais com expansão B2B para redes, franquias e distribuidores.",
    revenue: "R$ 28M",
    tax_identifier: "78.901.234/0001-56",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 7,
    name: "Instituto Horizonte",
    logo: logo(7, "Instituto Horizonte"),
    sector: "health-care",
    size: 50,
    linkedin_url: "https://www.linkedin.com/company/instituto-horizonte",
    website: "https://institutohorizonte.org.br",
    phone_number: "+55 61 3020-6611",
    address: "SHS Quadra 6 Conjunto A",
    zipcode: "70316-000",
    city: "Brasília",
    state_abbr: "DF",
    sales_id: 2,
    created_at: "2026-01-19T12:00:00.000Z",
    description:
      "Instituto educacional e social estruturando captação, parcerias e relacionamento com patrocinadores.",
    revenue: "R$ 14M",
    tax_identifier: "89.012.345/0001-67",
    country: "Brasil",
    context_links: ["https://institutohorizonte.org.br/transparencia"],
  },
  {
    id: 8,
    name: "Conecta Saúde",
    logo: logo(8, "Conecta Saúde"),
    sector: "information-technology",
    size: 50,
    linkedin_url: "https://www.linkedin.com/company/conecta-saude",
    website: "https://conectasaude.com.br",
    phone_number: "+55 51 3344-8080",
    address: "Av. Carlos Gomes, 700",
    zipcode: "90480-000",
    city: "Porto Alegre",
    state_abbr: "RS",
    sales_id: 5,
    created_at: "2026-02-01T12:00:00.000Z",
    description:
      "Healthtech B2B com equipe enxuta e necessidade de previsibilidade no relacionamento com hospitais.",
    revenue: "R$ 21M",
    tax_identifier: "90.123.456/0001-78",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 9,
    name: "Armazém Urbano",
    logo: logo(9, "Armazém Urbano"),
    sector: "consumer-discretionary",
    size: 10,
    linkedin_url: "https://www.linkedin.com/company/armazem-urbano",
    website: "https://armazemurbano.com.br",
    phone_number: "+55 11 3090-7755",
    address: "Rua Harmonia, 231",
    zipcode: "05435-000",
    city: "São Paulo",
    state_abbr: "SP",
    sales_id: 0,
    created_at: "2026-02-14T12:00:00.000Z",
    description:
      "Rede de lojas de bairro testando operação omnichannel e relacionamento com assinantes recorrentes.",
    revenue: "R$ 9M",
    tax_identifier: "01.234.567/0001-89",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 10,
    name: "Zenith Educação",
    logo: logo(10, "Zenith Educação"),
    sector: "communication-services",
    size: 250,
    linkedin_url: "https://www.linkedin.com/company/zenith-educacao",
    website: "https://zenitheducacao.com.br",
    phone_number: "+55 81 3131-6060",
    address: "Rua do Bom Jesus, 183",
    zipcode: "50030-170",
    city: "Recife",
    state_abbr: "PE",
    sales_id: 3,
    created_at: "2026-03-03T12:00:00.000Z",
    description:
      "Grupo de cursos livres com funil de matrículas corporativas e renovação recorrente por turma.",
    revenue: "R$ 63M",
    tax_identifier: "11.222.333/0001-44",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 11,
    name: "Metal Forte",
    logo: logo(11, "Metal Forte"),
    sector: "materials",
    size: 500,
    linkedin_url: "https://www.linkedin.com/company/metal-forte",
    website: "https://metalforte.ind.br",
    phone_number: "+55 19 3777-4411",
    address: "Rod. Anhanguera, km 104",
    zipcode: "13069-901",
    city: "Campinas",
    state_abbr: "SP",
    sales_id: 4,
    created_at: "2026-03-17T12:00:00.000Z",
    description:
      "Indústria metalúrgica em modernização comercial, com representantes externos e alto ticket médio.",
    revenue: "R$ 210M",
    tax_identifier: "22.333.444/0001-55",
    country: "Brasil",
    context_links: ["https://metalforte.ind.br/sustentabilidade"],
  },
  {
    id: 12,
    name: "Casa Riviera",
    logo: logo(12, "Casa Riviera"),
    sector: "real-estate",
    size: 10,
    linkedin_url: "https://www.linkedin.com/company/casa-riviera",
    website: "https://casariviera.com.br",
    phone_number: "+55 13 3201-3000",
    address: "Av. Ana Costa, 433",
    zipcode: "11060-003",
    city: "Santos",
    state_abbr: "SP",
    sales_id: 5,
    created_at: "2026-04-02T12:00:00.000Z",
    description:
      "Imobiliária boutique buscando automatizar captação, visitas e relacionamento pós-venda.",
    revenue: "R$ 7M",
    tax_identifier: "33.444.555/0001-66",
    country: "Brasil",
    context_links: [],
  },
  {
    id: 13,
    name: "Omnix Tech",
    logo: logo(13, "Omnix Tech"),
    sector: "information-technology",
    size: 50,
    linkedin_url: "https://www.linkedin.com/company/omnix-tech",
    website: "https://omnixtech.com.br",
    phone_number: "+55 11 4550-9191",
    address: "Alameda Santos, 1293",
    zipcode: "01419-002",
    city: "São Paulo",
    state_abbr: "SP",
    sales_id: 2,
    created_at: "2026-04-20T12:00:00.000Z",
    description:
      "SaaS de atendimento procurando integrar pré-venda, propostas e expansão de contas estratégicas.",
    revenue: "R$ 36M",
    tax_identifier: "44.555.666/0001-77",
    country: "Brasil",
    context_links: ["https://omnixtech.com.br/status"],
  },
];

export const generateCompanies = (_db: Db): Required<Company>[] =>
  companies.map((company) => ({
    ...company,
    nb_contacts: 0,
    nb_deals: 0,
  }));
