--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    workspace_id uuid not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.pipelines (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    name text not null,
    stages jsonb not null default '[]'::jsonb,
    created_at timestamp with time zone not null default now()
);

create table public.deals (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    deal_type text not null default 'consultative',
    probability smallint default 25,
    source text,
    lost_reason text,
    next_action_at timestamp with time zone,
    last_activity_at timestamp with time zone default now(),
    pipeline_id bigint references public.pipelines(id),
    constraint deals_probability_range check (
        probability is null or (probability >= 0 and probability <= 100)
    )
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    workspace_id uuid not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.leads (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    first_name text not null,
    last_name text,
    email extensions.citext,
    phone_number text,
    company_name text,
    source text,
    interest text,
    temperature text not null default 'warm',
    status text not null default 'new',
    next_action_at timestamp with time zone,
    discard_reason text,
    converted_at timestamp with time zone,
    discarded_at timestamp with time zone,
    sales_id bigint,
    constraint leads_temperature_check check (temperature in ('cold', 'warm', 'hot')),
    constraint leads_status_check check (status in ('new', 'contacted', 'qualified', 'converted', 'discarded'))
);

create table public.sales (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    clerk_user_id text not null,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    workspace_role text not null default 'member',
    product_role text not null default 'member',
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__workspace_clerk_user on public.sales using btree (workspace_id, clerk_user_id);

create table public.sales_goals (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    sales_id bigint not null,
    period_start date not null,
    revenue_goal bigint not null default 0,
    won_deals_goal integer not null default 0,
    sent_proposals_goal integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sales_goals_values_check check (revenue_goal >= 0 and won_deals_goal >= 0 and sent_proposals_goal >= 0),
    constraint sales_goals_month_start_check check (period_start = date_trunc('month', period_start)::date)
);

create table public.tags (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    name text not null,
    color text not null
);

create table public.automation_runs (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    created_at timestamp with time zone not null default now(),
    rule_key text not null,
    trigger_resource text not null,
    trigger_record_id bigint not null,
    action_resource text,
    action_record_id bigint,
    status text not null default 'success',
    message text,
    sales_id bigint,
    constraint automation_runs_status_check check (status in ('success', 'skipped', 'failed'))
);

create unique index automation_runs_rule_trigger_idx
    on public.automation_runs using btree (workspace_id, rule_key, trigger_resource, trigger_record_id);

create table public.proposal_templates (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    name text not null,
    description text,
    default_scope text,
    default_terms text,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.proposal_template_items (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    template_id bigint not null,
    description text not null,
    quantity numeric not null default 1,
    unit_price bigint not null default 0,
    discount_amount bigint not null default 0,
    index smallint not null default 0,
    constraint proposal_template_items_amounts_check check (quantity > 0 and unit_price >= 0 and discount_amount >= 0)
);

create table public.proposals (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    deal_id bigint not null,
    company_id bigint not null,
    contact_id bigint,
    sales_id bigint,
    template_id bigint,
    number text not null,
    title text not null,
    status text not null default 'draft',
    scope text,
    terms text,
    internal_notes text,
    delivery_time text,
    payment_terms text,
    currency text not null default 'BRL',
    subtotal bigint not null default 0,
    discount_amount bigint not null default 0,
    tax_amount bigint not null default 0,
    total bigint not null default 0,
    valid_until date,
    sent_at timestamp with time zone,
    accepted_at timestamp with time zone,
    rejected_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint proposals_status_check check (status in ('draft', 'sent', 'accepted', 'rejected', 'expired')),
    constraint proposals_amounts_check check (subtotal >= 0 and discount_amount >= 0 and tax_amount >= 0 and total >= 0)
);

create table public.proposal_items (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    proposal_id bigint not null,
    description text not null,
    quantity numeric not null default 1,
    unit_price bigint not null default 0,
    discount_amount bigint not null default 0,
    total bigint not null default 0,
    index smallint not null default 0,
    constraint proposal_items_amounts_check check (quantity > 0 and unit_price >= 0 and discount_amount >= 0 and total >= 0)
);

create table public.automation_rules (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    rule_key text not null,
    name text not null,
    description text,
    enabled boolean not null default true,
    trigger_resource text not null,
    trigger_event text not null,
    condition_key text,
    action_key text not null,
    params jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    contact_id bigint,
    lead_id bigint,
    deal_id bigint,
    automation_run_id bigint,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.stage_task_templates (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    pipeline_id bigint not null references public.pipelines(id) on update cascade on delete cascade,
    stage text not null,
    name text not null,
    task_text text not null,
    task_type text not null default 'follow-up',
    due_in_days integer not null default 0,
    mode text not null default 'manual',
    enabled boolean not null default true,
    instructions text,
    assignee text not null default 'record_owner',
    index smallint not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint stage_task_templates_due_in_days_check check (due_in_days >= 0),
    constraint stage_task_templates_mode_check check (mode in ('manual', 'automatic')),
    constraint stage_task_templates_assignee_check check (assignee in ('record_owner'))
);

create table public.configuration (
    id integer generated by default as identity primary key,
    workspace_id uuid not null,
    config jsonb not null default '{}'::jsonb
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sales_goals
    add constraint sales_goals_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.automation_runs
    add constraint automation_runs_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.proposals
    add constraint proposals_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.proposals
    add constraint proposals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.proposals
    add constraint proposals_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.proposals
    add constraint proposals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.proposals
    add constraint proposals_template_id_fkey foreign key (template_id) references public.proposal_templates(id);

alter table public.proposal_template_items
    add constraint proposal_template_items_template_id_fkey foreign key (template_id) references public.proposal_templates(id) on update cascade on delete cascade;

alter table public.proposal_items
    add constraint proposal_items_proposal_id_fkey foreign key (proposal_id) references public.proposals(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_lead_id_fkey foreign key (lead_id) references public.leads(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_automation_run_id_fkey foreign key (automation_run_id) references public.automation_runs(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index deals_pipeline_id_idx on public.deals using btree (pipeline_id);
create index leads_sales_id_idx on public.leads using btree (sales_id);
create index leads_status_idx on public.leads using btree (status);
create index sales_goals_sales_id_idx on public.sales_goals using btree (sales_id);
create unique index sales_goals_sales_period_idx on public.sales_goals using btree (sales_id, period_start);
create index proposals_deal_id_idx on public.proposals using btree (deal_id);
create index proposals_company_id_idx on public.proposals using btree (company_id);
create index proposals_sales_id_idx on public.proposals using btree (sales_id);
create index proposals_status_idx on public.proposals using btree (status);
create index proposals_valid_until_idx on public.proposals using btree (valid_until);
create index proposal_template_items_template_id_idx on public.proposal_template_items using btree (template_id);
create index proposal_items_proposal_id_idx on public.proposal_items using btree (proposal_id);
create index automation_rules_enabled_idx on public.automation_rules using btree (enabled);
create index tasks_contact_id_idx on public.tasks using btree (contact_id);
create index tasks_lead_id_idx on public.tasks using btree (lead_id);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create index stage_task_templates_workspace_id_idx on public.stage_task_templates using btree (workspace_id);
create index stage_task_templates_lookup_idx on public.stage_task_templates using btree (workspace_id, pipeline_id, stage, enabled);
create index stage_task_templates_order_idx on public.stage_task_templates using btree (workspace_id, pipeline_id, stage, index);
create unique index configuration_workspace_id_idx on public.configuration using btree (workspace_id);
create unique index automation_rules_workspace_rule_key_idx on public.automation_rules using btree (workspace_id, rule_key);

create index companies_workspace_id_idx on public.companies using btree (workspace_id);
create index contacts_workspace_id_idx on public.contacts using btree (workspace_id);
create index contact_notes_workspace_id_idx on public.contact_notes using btree (workspace_id);
create index pipelines_workspace_id_idx on public.pipelines using btree (workspace_id);
create index deals_workspace_id_idx on public.deals using btree (workspace_id);
create index deal_notes_workspace_id_idx on public.deal_notes using btree (workspace_id);
create index leads_workspace_id_idx on public.leads using btree (workspace_id);
create index sales_workspace_id_idx on public.sales using btree (workspace_id);
create index sales_goals_workspace_id_idx on public.sales_goals using btree (workspace_id);
create index tags_workspace_id_idx on public.tags using btree (workspace_id);
create index automation_runs_workspace_id_idx on public.automation_runs using btree (workspace_id);
create index proposal_templates_workspace_id_idx on public.proposal_templates using btree (workspace_id);
create index proposal_template_items_workspace_id_idx on public.proposal_template_items using btree (workspace_id);
create index proposals_workspace_id_idx on public.proposals using btree (workspace_id);
create index proposal_items_workspace_id_idx on public.proposal_items using btree (workspace_id);
create index automation_rules_workspace_id_idx on public.automation_rules using btree (workspace_id);
create index tasks_workspace_id_idx on public.tasks using btree (workspace_id);
create index favicons_excluded_domains_workspace_id_idx on public.favicons_excluded_domains using btree (workspace_id);
