set check_function_bodies = off;

do $$
declare
  default_workspace_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  tenant_table text;
begin
  alter table if exists public.sales drop constraint if exists sales_user_id_fkey;

  drop trigger if exists on_auth_user_created on auth.users;
  drop trigger if exists on_auth_user_updated on auth.users;
  drop function if exists public.handle_new_user();
  drop function if exists public.handle_update_user();
  drop function if exists public.get_user_id_by_email(text);

  foreach tenant_table in array array[
    'companies',
    'contacts',
    'contact_notes',
    'pipelines',
    'deals',
    'deal_notes',
    'leads',
    'sales',
    'sales_goals',
    'tags',
    'automation_runs',
    'proposal_templates',
    'proposal_template_items',
    'proposals',
    'proposal_items',
    'automation_rules',
    'tasks',
    'configuration',
    'favicons_excluded_domains'
  ]
  loop
    execute format('alter table public.%I add column if not exists workspace_id uuid', tenant_table);
    execute format('update public.%I set workspace_id = %L::uuid where workspace_id is null', tenant_table, default_workspace_id);
    execute format('alter table public.%I alter column workspace_id set not null', tenant_table);
    execute format(
      'create index if not exists %I on public.%I using btree (workspace_id)',
      tenant_table || '_workspace_id_idx',
      tenant_table
    );
  end loop;
end;
$$;

alter table public.sales
  add column if not exists clerk_user_id text,
  add column if not exists workspace_role text not null default 'member',
  add column if not exists product_role text not null default 'member';

update public.sales
set clerk_user_id = coalesce(clerk_user_id, email::text)
where clerk_user_id is null;

alter table public.sales
  alter column clerk_user_id set not null;

drop index if exists public.uq__sales__user_id;
create unique index if not exists uq__sales__workspace_clerk_user
  on public.sales using btree (workspace_id, clerk_user_id);

alter table public.sales
  drop column if exists user_id;

alter table public.configuration
  drop constraint if exists configuration_singleton,
  alter column id drop default;

do $$
declare
  next_configuration_id bigint;
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'configuration'
      and column_name = 'id'
      and identity_generation is null
  ) then
    select coalesce(max(id), 0) + 1 into next_configuration_id
    from public.configuration;

    execute format(
      'alter table public.configuration alter column id add generated by default as identity (start with %s)',
      greatest(next_configuration_id, 1)
    );
  end if;
end;
$$;

create unique index if not exists configuration_workspace_id_idx
  on public.configuration using btree (workspace_id);

drop index if exists public.automation_runs_rule_trigger_idx;
create unique index if not exists automation_runs_rule_trigger_idx
  on public.automation_runs using btree (workspace_id, rule_key, trigger_resource, trigger_record_id);

alter table public.automation_rules
  drop constraint if exists automation_rules_rule_key_key;

create unique index if not exists automation_rules_workspace_rule_key_idx
  on public.automation_rules using btree (workspace_id, rule_key);

create or replace function public.current_clerk_user_id() returns text
  language sql
  stable
  set search_path to ''
as $$
  select nullif(auth.jwt() ->> 'sub', '');
$$;

create or replace function public.can_access_workspace(target_workspace_id uuid) returns boolean
  language plpgsql
  security definer
  set search_path to ''
as $$
begin
  if target_workspace_id is null then
    return false;
  end if;

  return exists (
    select 1
    from public.sales
    where workspace_id = target_workspace_id
      and clerk_user_id = public.current_clerk_user_id()
      and disabled = false
  );
end;
$$;

create or replace function public.current_sale_id(target_workspace_id uuid) returns bigint
  language plpgsql
  security definer
  set search_path to ''
as $$
declare
  sale_id bigint;
begin
  if target_workspace_id is null then
    return null;
  end if;

  select id into sale_id
  from public.sales
  where workspace_id = target_workspace_id
    and clerk_user_id = public.current_clerk_user_id()
    and disabled = false
  order by id
  limit 1;

  return sale_id;
end;
$$;

create or replace function public.is_admin_for_workspace(target_workspace_id uuid) returns boolean
  language plpgsql
  security definer
  set search_path to ''
as $$
begin
  if target_workspace_id is null then
    return false;
  end if;

  return exists (
    select 1
    from public.sales
    where workspace_id = target_workspace_id
      and clerk_user_id = public.current_clerk_user_id()
      and disabled = false
      and (
        administrator = true
        or workspace_role in ('admin', 'administrator', 'owner')
        or product_role in ('admin', 'administrator', 'owner')
      )
  );
end;
$$;

create or replace function public.is_admin() returns boolean
  language plpgsql
  security definer
  set search_path to ''
as $$
begin
  return exists (
    select 1
    from public.sales
    where clerk_user_id = public.current_clerk_user_id()
      and disabled = false
      and (
        administrator = true
        or workspace_role in ('admin', 'administrator', 'owner')
        or product_role in ('admin', 'administrator', 'owner')
      )
  );
end;
$$;

create or replace function public.set_sales_id_default() returns trigger
  language plpgsql
  set search_path to ''
as $$
begin
  if new.sales_id is null and new.workspace_id is not null then
    new.sales_id := public.current_sale_id(new.workspace_id);
  end if;

  return new;
end;
$$;

create or replace function public.handle_contact_note_created_or_updated() returns trigger
  language plpgsql
  security definer
  set search_path to ''
as $$
begin
  update public.contacts
  set last_seen = new.date
  where contacts.id = new.contact_id
    and contacts.workspace_id = new.workspace_id
    and contacts.last_seen < new.date;
  return new;
end;
$$;

drop view if exists public.activity_log;
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

create or replace view public.activity_log with (security_invoker = on) as
select
    ('company.' || c.id || '.created') as id,
    c.workspace_id,
    'company.created' as type,
    c.created_at as date,
    c.id as company_id,
    c.sales_id,
    to_json(c.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.companies c
union all
select
    ('contact.' || co.id || '.created') as id,
    co.workspace_id,
    'contact.created' as type,
    co.first_seen as date,
    co.company_id,
    co.sales_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    cn.workspace_id,
    'contactNote.created' as type,
    cn.date,
    co.company_id,
    cn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note
from public.contact_notes cn
    left join public.contacts co on co.id = cn.contact_id and co.workspace_id = cn.workspace_id
union all
select
    ('deal.' || d.id || '.created') as id,
    d.workspace_id,
    'deal.created' as type,
    d.created_at as date,
    d.company_id,
    d.sales_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    dn.workspace_id,
    'dealNote.created' as type,
    dn.date,
    d.company_id,
    dn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note
from public.deal_notes dn
    left join public.deals d on d.id = dn.deal_id and d.workspace_id = dn.workspace_id;

create or replace view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.workspace_id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id and c.workspace_id = d.workspace_id
    left join public.contacts co on c.id = co.company_id and c.workspace_id = co.workspace_id
group by c.id;

create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.workspace_id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id and co.workspace_id = t.workspace_id
    left join public.companies c on co.company_id = c.id and co.workspace_id = c.workspace_id
group by co.id, c.name;

do $$
declare
  tenant_table text;
  policy_name text;
begin
  foreach tenant_table in array array[
    'companies',
    'contacts',
    'contact_notes',
    'pipelines',
    'deals',
    'deal_notes',
    'leads',
    'sales',
    'sales_goals',
    'tags',
    'automation_runs',
    'proposal_templates',
    'proposal_template_items',
    'proposals',
    'proposal_items',
    'automation_rules',
    'tasks',
    'configuration',
    'favicons_excluded_domains'
  ]
  loop
    execute format('alter table public.%I enable row level security', tenant_table);

    for policy_name in
      select policyname
      from pg_policies
      where schemaname = 'public'
        and tablename = tenant_table
    loop
      execute format('drop policy if exists %I on public.%I', policy_name, tenant_table);
    end loop;
  end loop;
end;
$$;

create policy "Tenant read" on public.companies for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.companies for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.companies for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.companies for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.contacts for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.contacts for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.contacts for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.contacts for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.contact_notes for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.contact_notes for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.contact_notes for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.contact_notes for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.pipelines for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.pipelines for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.pipelines for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.pipelines for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.deals for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.deals for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.deals for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.deals for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.deal_notes for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.deal_notes for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.deal_notes for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.deal_notes for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.leads for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.leads for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.leads for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.leads for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.tags for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.tags for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.tags for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.tags for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.automation_runs for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.automation_runs for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.automation_runs for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.automation_runs for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.proposals for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.proposals for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.proposals for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.proposals for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.proposal_items for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.proposal_items for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.proposal_items for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.proposal_items for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.tasks for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Tenant insert" on public.tasks for insert to authenticated with check (public.can_access_workspace(workspace_id));
create policy "Tenant update" on public.tasks for update to authenticated using (public.can_access_workspace(workspace_id)) with check (public.can_access_workspace(workspace_id));
create policy "Tenant delete" on public.tasks for delete to authenticated using (public.can_access_workspace(workspace_id));

create policy "Tenant read" on public.sales for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.sales for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.sales for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.sales for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.sales_goals for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.sales_goals for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.sales_goals for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.sales_goals for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.proposal_templates for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.proposal_templates for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.proposal_templates for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.proposal_templates for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.proposal_template_items for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.proposal_template_items for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.proposal_template_items for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.proposal_template_items for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.automation_rules for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.automation_rules for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.automation_rules for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.automation_rules for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.configuration for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.configuration for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.configuration for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.configuration for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

create policy "Tenant read" on public.favicons_excluded_domains for select to authenticated using (public.can_access_workspace(workspace_id));
create policy "Admin insert" on public.favicons_excluded_domains for insert to authenticated with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin update" on public.favicons_excluded_domains for update to authenticated using (public.is_admin_for_workspace(workspace_id)) with check (public.is_admin_for_workspace(workspace_id));
create policy "Admin delete" on public.favicons_excluded_domains for delete to authenticated using (public.is_admin_for_workspace(workspace_id));

grant all on function public.current_clerk_user_id() to anon, authenticated, service_role;
grant all on function public.can_access_workspace(uuid) to anon, authenticated, service_role;
grant all on function public.current_sale_id(uuid) to anon, authenticated, service_role;
grant all on function public.is_admin_for_workspace(uuid) to anon, authenticated, service_role;
grant all on function public.is_admin() to anon, authenticated, service_role;
grant all on function public.set_sales_id_default() to anon, authenticated, service_role;

grant all on table public.pipelines to anon, authenticated, service_role;
grant all on sequence public.pipelines_id_seq to anon, authenticated, service_role;

grant all on table public.activity_log to anon, authenticated, service_role;
grant all on table public.companies_summary to anon, authenticated, service_role;
grant all on table public.contacts_summary to anon, authenticated, service_role;
