create table public.proposal_templates (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    default_scope text,
    default_terms text,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.proposals (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    company_id bigint not null,
    contact_id bigint,
    sales_id bigint,
    template_id bigint,
    number text not null,
    title text not null,
    status text not null default 'draft',
    scope text,
    terms text,
    currency text not null default 'BRL',
    subtotal bigint not null default 0,
    discount_amount bigint not null default 0,
    total bigint not null default 0,
    valid_until date,
    sent_at timestamp with time zone,
    accepted_at timestamp with time zone,
    rejected_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint proposals_status_check check (status in ('draft', 'sent', 'accepted', 'rejected', 'expired')),
    constraint proposals_amounts_check check (subtotal >= 0 and discount_amount >= 0 and total >= 0)
);

create table public.proposal_items (
    id bigint generated by default as identity primary key,
    proposal_id bigint not null,
    description text not null,
    quantity numeric not null default 1,
    unit_price bigint not null default 0,
    discount_amount bigint not null default 0,
    total bigint not null default 0,
    index smallint not null default 0,
    constraint proposal_items_amounts_check check (quantity > 0 and unit_price >= 0 and discount_amount >= 0 and total >= 0)
);

create table public.automation_rules (
    id bigint generated by default as identity primary key,
    rule_key text not null unique,
    name text not null,
    description text,
    enabled boolean not null default true,
    trigger_resource text not null,
    trigger_event text not null,
    condition_key text,
    action_key text not null,
    params jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.proposals add constraint proposals_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.proposals add constraint proposals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;
alter table public.proposals add constraint proposals_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;
alter table public.proposals add constraint proposals_sales_id_fkey foreign key (sales_id) references public.sales(id);
alter table public.proposals add constraint proposals_template_id_fkey foreign key (template_id) references public.proposal_templates(id);
alter table public.proposal_items add constraint proposal_items_proposal_id_fkey foreign key (proposal_id) references public.proposals(id) on update cascade on delete cascade;

create index proposals_deal_id_idx on public.proposals using btree (deal_id);
create index proposals_company_id_idx on public.proposals using btree (company_id);
create index proposals_sales_id_idx on public.proposals using btree (sales_id);
create index proposals_status_idx on public.proposals using btree (status);
create index proposals_valid_until_idx on public.proposals using btree (valid_until);
create index proposal_items_proposal_id_idx on public.proposal_items using btree (proposal_id);
create index automation_rules_enabled_idx on public.automation_rules using btree (enabled);

alter table public.proposal_templates enable row level security;
alter table public.proposals enable row level security;
alter table public.proposal_items enable row level security;
alter table public.automation_rules enable row level security;

create policy "Enable read access for authenticated users" on public.proposal_templates for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.proposal_templates for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.proposal_templates for update to authenticated using (true) with check (true);
create policy "Proposal Templates Delete Policy" on public.proposal_templates for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.proposals for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.proposals for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.proposals for update to authenticated using (true) with check (true);
create policy "Proposals Delete Policy" on public.proposals for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.proposal_items for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.proposal_items for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.proposal_items for update to authenticated using (true) with check (true);
create policy "Proposal Items Delete Policy" on public.proposal_items for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.automation_rules for select to authenticated using (true);
create policy "Enable insert for admins" on public.automation_rules for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.automation_rules for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Automation Rules Delete Policy" on public.automation_rules for delete to authenticated using (public.is_admin());

grant all on table public.proposal_templates to anon;
grant all on table public.proposal_templates to authenticated;
grant all on table public.proposal_templates to service_role;

grant all on table public.proposals to anon;
grant all on table public.proposals to authenticated;
grant all on table public.proposals to service_role;

grant all on table public.proposal_items to anon;
grant all on table public.proposal_items to authenticated;
grant all on table public.proposal_items to service_role;

grant all on table public.automation_rules to anon;
grant all on table public.automation_rules to authenticated;
grant all on table public.automation_rules to service_role;

grant all on sequence public.proposal_templates_id_seq to anon;
grant all on sequence public.proposal_templates_id_seq to authenticated;
grant all on sequence public.proposal_templates_id_seq to service_role;

grant all on sequence public.proposals_id_seq to anon;
grant all on sequence public.proposals_id_seq to authenticated;
grant all on sequence public.proposals_id_seq to service_role;

grant all on sequence public.proposal_items_id_seq to anon;
grant all on sequence public.proposal_items_id_seq to authenticated;
grant all on sequence public.proposal_items_id_seq to service_role;

grant all on sequence public.automation_rules_id_seq to anon;
grant all on sequence public.automation_rules_id_seq to authenticated;
grant all on sequence public.automation_rules_id_seq to service_role;

insert into public.proposal_templates (name, description, default_scope, default_terms, active)
values (
    'Proposta comercial padrao',
    'Template simples para propostas comerciais',
    'Escopo comercial a ser ajustado pelo vendedor.',
    'Esta proposta e valida ate a data indicada e pode ser revisada conforme alinhamento comercial.',
    true
);

insert into public.automation_rules (rule_key, name, description, enabled, trigger_resource, trigger_event, condition_key, action_key, params)
values
    ('lead.first-contact', 'Lead sem próxima ação', 'Cria tarefa de primeiro contato quando um lead nasce sem próxima ação.', true, 'leads', 'created', 'missing_next_action', 'create_task', '{"dueInDays":0,"taskType":"call","taskText":"Primeiro contato com {{lead.name}}","assignee":"record_owner"}'::jsonb),
    ('deal.follow-up-required', 'Negócio sem próxima ação', 'Cria follow-up quando um negócio nasce sem próxima ação.', true, 'deals', 'created', 'missing_next_action', 'create_task', '{"dueInDays":1,"taskType":"follow-up","taskText":"Definir próximo passo: {{deal.name}}","assignee":"record_owner"}'::jsonb),
    ('deal.proposal-follow-up', 'Negócio em proposta enviada', 'Cria follow-up quando o negócio entra na etapa Proposta enviada.', true, 'deals', 'updated', 'stage_is_proposal_sent', 'create_task', '{"dueInDays":2,"taskType":"follow-up","taskText":"Retomar proposta enviada: {{deal.name}}","assignee":"record_owner"}'::jsonb),
    ('proposal.sent-follow-up', 'Proposta enviada', 'Cria follow-up depois que uma proposta é marcada como enviada.', true, 'proposals', 'updated', 'status_is_sent', 'create_task', '{"dueInDays":2,"taskType":"follow-up","taskText":"Acompanhar proposta: {{proposal.title}}","assignee":"record_owner"}'::jsonb),
    ('proposal.accepted-action', 'Proposta aceita', 'Executa a ação configurada quando uma proposta é aceita.', true, 'proposals', 'updated', 'status_is_accepted', 'proposal_accepted_action', '{"acceptedAction":"move_deal_won","taskType":"follow-up","taskText":"Concluir fechamento da proposta: {{proposal.title}}","assignee":"record_owner"}'::jsonb);
