create table "public"."leads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text,
    "email" extensions.citext,
    "phone_number" text,
    "company_name" text,
    "source" text,
    "interest" text,
    "temperature" text not null default 'warm'::text,
    "status" text not null default 'new'::text,
    "next_action_at" timestamp with time zone,
    "discard_reason" text,
    "converted_at" timestamp with time zone,
    "discarded_at" timestamp with time zone,
    "sales_id" bigint
);

alter table "public"."leads" enable row level security;

CREATE INDEX leads_sales_id_idx ON public.leads USING btree (sales_id);

CREATE INDEX leads_status_idx ON public.leads USING btree (status);

CREATE UNIQUE INDEX leads_pkey ON public.leads USING btree (id);

alter table "public"."leads" add constraint "leads_pkey" primary key using index "leads_pkey";

alter table "public"."leads" add constraint "leads_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;

alter table "public"."leads" validate constraint "leads_sales_id_fkey";

alter table "public"."leads" add constraint "leads_status_check" CHECK ((status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'converted'::text, 'discarded'::text]))) not valid;

alter table "public"."leads" validate constraint "leads_status_check";

alter table "public"."leads" add constraint "leads_temperature_check" CHECK ((temperature = ANY (ARRAY['cold'::text, 'warm'::text, 'hot'::text]))) not valid;

alter table "public"."leads" validate constraint "leads_temperature_check";

set check_function_bodies = off;

CREATE OR REPLACE TRIGGER set_lead_sales_id_trigger BEFORE INSERT ON public.leads FOR EACH ROW EXECUTE FUNCTION set_sales_id_default();

grant all on table "public"."leads" to "anon";

grant all on table "public"."leads" to "authenticated";

grant all on table "public"."leads" to "service_role";

grant all on sequence "public"."leads_id_seq" to "anon";

grant all on sequence "public"."leads_id_seq" to "authenticated";

grant all on sequence "public"."leads_id_seq" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."leads"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable read access for authenticated users"
on "public"."leads"
as permissive
for select
to authenticated
using (true);

create policy "Enable update for authenticated users only"
on "public"."leads"
as permissive
for update
to authenticated
using (true)
with check (true);

create policy "Leads Delete Policy"
on "public"."leads"
as permissive
for delete
to authenticated
using (true);
