alter table public.proposals
    add column if not exists internal_notes text,
    add column if not exists delivery_time text,
    add column if not exists payment_terms text,
    add column if not exists tax_amount bigint not null default 0;

alter table public.proposals
    drop constraint if exists proposals_amounts_check;

alter table public.proposals
    add constraint proposals_amounts_check check (subtotal >= 0 and discount_amount >= 0 and tax_amount >= 0 and total >= 0);

create table if not exists public.proposal_template_items (
    id bigint generated by default as identity primary key,
    template_id bigint not null,
    description text not null,
    quantity numeric not null default 1,
    unit_price bigint not null default 0,
    discount_amount bigint not null default 0,
    index smallint not null default 0,
    constraint proposal_template_items_amounts_check check (quantity > 0 and unit_price >= 0 and discount_amount >= 0)
);

create table if not exists public.sales_goals (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    period_start date not null,
    revenue_goal bigint not null default 0,
    won_deals_goal integer not null default 0,
    sent_proposals_goal integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sales_goals_values_check check (revenue_goal >= 0 and won_deals_goal >= 0 and sent_proposals_goal >= 0),
    constraint sales_goals_month_start_check check (period_start = date_trunc('month', period_start)::date)
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'proposal_template_items_template_id_fkey'
          and conrelid = 'public.proposal_template_items'::regclass
    ) then
        alter table public.proposal_template_items
            add constraint proposal_template_items_template_id_fkey foreign key (template_id) references public.proposal_templates(id) on update cascade on delete cascade;
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'sales_goals_sales_id_fkey'
          and conrelid = 'public.sales_goals'::regclass
    ) then
        alter table public.sales_goals
            add constraint sales_goals_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;
    end if;
end;
$$;

create index if not exists proposal_template_items_template_id_idx on public.proposal_template_items using btree (template_id);
create index if not exists sales_goals_sales_id_idx on public.sales_goals using btree (sales_id);
create unique index if not exists sales_goals_sales_period_idx on public.sales_goals using btree (sales_id, period_start);

alter table public.proposal_template_items enable row level security;
alter table public.sales_goals enable row level security;

drop policy if exists "Enable read access for authenticated users" on public.proposal_templates;
drop policy if exists "Enable insert for authenticated users only" on public.proposal_templates;
drop policy if exists "Enable update for authenticated users only" on public.proposal_templates;
drop policy if exists "Enable insert for admins" on public.proposal_templates;
drop policy if exists "Enable update for admins" on public.proposal_templates;
drop policy if exists "Proposal Templates Delete Policy" on public.proposal_templates;

create policy "Enable read access for authenticated users" on public.proposal_templates for select to authenticated using (true);
create policy "Enable insert for admins" on public.proposal_templates for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.proposal_templates for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Proposal Templates Delete Policy" on public.proposal_templates for delete to authenticated using (public.is_admin());

drop policy if exists "Enable read access for authenticated users" on public.proposal_template_items;
drop policy if exists "Enable insert for admins" on public.proposal_template_items;
drop policy if exists "Enable update for admins" on public.proposal_template_items;
drop policy if exists "Proposal Template Items Delete Policy" on public.proposal_template_items;

create policy "Enable read access for authenticated users" on public.proposal_template_items for select to authenticated using (true);
create policy "Enable insert for admins" on public.proposal_template_items for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.proposal_template_items for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Proposal Template Items Delete Policy" on public.proposal_template_items for delete to authenticated using (public.is_admin());

drop policy if exists "Enable read access for authenticated users" on public.sales_goals;
drop policy if exists "Enable insert for admins" on public.sales_goals;
drop policy if exists "Enable update for admins" on public.sales_goals;
drop policy if exists "Sales Goals Delete Policy" on public.sales_goals;

create policy "Enable read access for authenticated users" on public.sales_goals for select to authenticated using (true);
create policy "Enable insert for admins" on public.sales_goals for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.sales_goals for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Sales Goals Delete Policy" on public.sales_goals for delete to authenticated using (public.is_admin());

grant all on table public.proposal_template_items to anon;
grant all on table public.proposal_template_items to authenticated;
grant all on table public.proposal_template_items to service_role;

grant all on table public.sales_goals to anon;
grant all on table public.sales_goals to authenticated;
grant all on table public.sales_goals to service_role;

grant all on sequence public.proposal_template_items_id_seq to anon;
grant all on sequence public.proposal_template_items_id_seq to authenticated;
grant all on sequence public.proposal_template_items_id_seq to service_role;

grant all on sequence public.sales_goals_id_seq to anon;
grant all on sequence public.sales_goals_id_seq to authenticated;
grant all on sequence public.sales_goals_id_seq to service_role;
