create table "public"."automation_runs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "rule_key" text not null,
    "trigger_resource" text not null,
    "trigger_record_id" bigint not null,
    "action_resource" text,
    "action_record_id" bigint,
    "status" text not null default 'success'::text,
    "message" text,
    "sales_id" bigint
);

alter table "public"."automation_runs" enable row level security;

alter table "public"."automation_runs"
    add constraint "automation_runs_pkey" primary key ("id");

alter table "public"."automation_runs"
    add constraint "automation_runs_status_check" check (status in ('success'::text, 'skipped'::text, 'failed'::text)) not valid;

alter table "public"."automation_runs" validate constraint "automation_runs_status_check";

create unique index automation_runs_rule_trigger_idx
    on public.automation_runs using btree (rule_key, trigger_resource, trigger_record_id);

alter table "public"."automation_runs"
    add constraint "automation_runs_sales_id_fkey" foreign key (sales_id) references public.sales(id) not valid;

alter table "public"."automation_runs" validate constraint "automation_runs_sales_id_fkey";

alter table "public"."tasks" alter column "contact_id" drop not null;

alter table "public"."tasks" add column "lead_id" bigint;

alter table "public"."tasks" add column "deal_id" bigint;

alter table "public"."tasks" add column "automation_run_id" bigint;

alter table "public"."tasks"
    add constraint "tasks_lead_id_fkey" foreign key (lead_id) references public.leads(id) on update cascade on delete cascade not valid;

alter table "public"."tasks" validate constraint "tasks_lead_id_fkey";

alter table "public"."tasks"
    add constraint "tasks_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade not valid;

alter table "public"."tasks" validate constraint "tasks_deal_id_fkey";

alter table "public"."tasks"
    add constraint "tasks_automation_run_id_fkey" foreign key (automation_run_id) references public.automation_runs(id) not valid;

alter table "public"."tasks" validate constraint "tasks_automation_run_id_fkey";

create index tasks_contact_id_idx on public.tasks using btree (contact_id);

create index tasks_lead_id_idx on public.tasks using btree (lead_id);

create index tasks_deal_id_idx on public.tasks using btree (deal_id);

grant all on table "public"."automation_runs" to "anon";
grant all on table "public"."automation_runs" to "authenticated";
grant all on table "public"."automation_runs" to "service_role";

grant all on sequence "public"."automation_runs_id_seq" to "anon";
grant all on sequence "public"."automation_runs_id_seq" to "authenticated";
grant all on sequence "public"."automation_runs_id_seq" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."automation_runs"
as permissive
for select
to authenticated
using (true);

create policy "Enable insert for authenticated users only"
on "public"."automation_runs"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on "public"."automation_runs"
as permissive
for update
to authenticated
using (true)
with check (true);
