-- Create pipelines table
create table if not exists public.pipelines (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone not null default now()
);

-- Insert default pipelines
insert into public.pipelines (name) values ('Vendas'), ('Pós-venda'), ('Parceiros');

-- Add pipeline_id to deals
alter table public.deals add column if not exists pipeline_id bigint references public.pipelines(id);

-- Assign all existing deals to the first pipeline (Vendas)
update public.deals set pipeline_id = (select id from public.pipelines where name = 'Vendas' limit 1) where pipeline_id is null;

-- Add stages column to pipelines
alter table public.pipelines add column if not exists stages jsonb not null default '[]'::jsonb;

-- Set default stages for existing pipelines
update public.pipelines set stages = '[
  {"value":"opportunity","label":"Oportunidade"},
  {"value":"proposal-sent","label":"Proposta enviada"},
  {"value":"in-negociation","label":"Em negociação"},
  {"value":"won","label":"Ganho"},
  {"value":"lost","label":"Perdido"},
  {"value":"delayed","label":"Adiado"}
]'::jsonb;
